/*
* json2
*/
var JSON;JSON||(JSON={});
(function(){function k(a){return a<10?"0"+a:a}function o(a){p.lastIndex=0;return p.test(a)?'"'+a.replace(p,function(a){var c=r[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(a,j){var c,d,h,m,g=e,f,b=j[a];b&&typeof b==="object"&&typeof b.toJSON==="function"&&(b=b.toJSON(a));typeof i==="function"&&(b=i.call(j,a,b));switch(typeof b){case "string":return o(b);case "number":return isFinite(b)?String(b):"null";case "boolean":case "null":return String(b);case "object":if(!b)return"null";
e+=n;f=[];if(Object.prototype.toString.apply(b)==="[object Array]"){m=b.length;for(c=0;c<m;c+=1)f[c]=l(c,b)||"null";h=f.length===0?"[]":e?"[\n"+e+f.join(",\n"+e)+"\n"+g+"]":"["+f.join(",")+"]";e=g;return h}if(i&&typeof i==="object"){m=i.length;for(c=0;c<m;c+=1)typeof i[c]==="string"&&(d=i[c],(h=l(d,b))&&f.push(o(d)+(e?": ":":")+h))}else for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(h=l(d,b))&&f.push(o(d)+(e?": ":":")+h);h=f.length===0?"{}":e?"{\n"+e+f.join(",\n"+e)+"\n"+g+"}":"{"+f.join(",")+
"}";e=g;return h}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+k(this.getUTCMonth()+1)+"-"+k(this.getUTCDate())+"T"+k(this.getUTCHours())+":"+k(this.getUTCMinutes())+":"+k(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var q=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
p=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,n,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,j,c){var d;n=e="";if(typeof c==="number")for(d=0;d<c;d+=1)n+=" ";else typeof c==="string"&&(n=c);if((i=j)&&typeof j!=="function"&&(typeof j!=="object"||typeof j.length!=="number"))throw Error("JSON.stringify");return l("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,e){function c(a,d){var g,f,b=a[d];if(b&&typeof b==="object")for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=c(b,g),f!==void 0?b[g]=f:delete b[g]);return e.call(a,d,b)}var d,a=String(a);q.lastIndex=0;q.test(a)&&(a=a.replace(q,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),typeof e==="function"?c({"":d},""):d;throw new SyntaxError("JSON.parse");}})();
/*
* jquery.iecors.js
*/
(function(b){b.ajaxSettings.xdr=function(){return window.XDomainRequest?new window.XDomainRequest:null};(function(a){b.extend(b.support,{iecors:!!a})})(b.ajaxSettings.xdr());b.support.iecors&&b.ajaxTransport(function(a){return{send:function(b,d){var c=a.xdr();c.onload=function(){d(200,"OK",{text:c.responseText},{"Content-Type":c.contentType})};if(a.xhrFields)xhr.onerror=a.xhrFields.error,xhr.ontimeout=a.xhrFields.timeout;c.open(a.type,a.url);c.send(a.hasContent&&a.data||null)},abort:function(){xdr.abort()}}})})(jQuery);
/*
* jquery.easydate.js
*/
(function(a){function c(a,c,b){!isNaN(c)&&c!=1&&(a+="s");return b.locale[a]||a}a.easydate={};a.easydate.locales={};a.easydate.locales.en={future_format:"%s %t",past_format:"%t %s",second:"second",seconds:"seconds",minute:"minute",minutes:"minutes",hour:"hour",hours:"hours",day:"day",days:"days",week:"week",weeks:"weeks",month:"month",months:"months",year:"year",years:"years",yesterday:"yesterday",tomorrow:"tomorrow",now:"just now",ago:"ago","in":"in"};a.easydate.locales.ca={future_format:"%s %t",
past_format:"%s %t",second:"segon",seconds:"segons",minute:"minut",minutes:"minuts",hour:"hora",hours:"hores",day:"dia",days:"dies",week:"setmana",weeks:"setmanes",month:"mes",months:"mesos",year:"any",years:"anys",yesterday:"ahir",tomorrow:"dem\u00e0",now:"fa un moment",ago:"fa","in":"en"};a.easydate.locales.es={future_format:"%s %t",past_format:"%s %t",second:"segundo",seconds:"segundos",minute:"minuto",minutes:"minutos",hour:"hora",hours:"horas",day:"dia",days:"dias",week:"semana",weeks:"semanas",
month:"mes",months:"meses",year:"a\u00f1o",years:"a\u00f1os",yesterday:"ayer",tomorrow:"ma\u00f1ana",now:"hace un instante",ago:"hace","in":"en"};var i={live:!0,set_title:!0,format_future:!0,format_past:!0,units:[{name:"now",limit:5},{name:"second",limit:60,in_seconds:1},{name:"minute",limit:3600,in_seconds:60},{name:"hour",limit:86400,in_seconds:3600},{name:"yesterday",limit:172800,past_only:!0},{name:"tomorrow",limit:172800,future_only:!0},{name:"day",limit:604800,in_seconds:86400},{name:"week",
limit:2629743,in_seconds:604800},{name:"month",limit:31556926,in_seconds:2629743},{name:"year",limit:Infinity,in_seconds:31556926}],uneasy_format:function(a){return a.toLocaleDateString()},locale:a.easydate.locales.en};a.easydate.format_date=function(g,h){var b=a.extend({},i);b.locale=a.easydate.locales[h];var d=((new Date).getTime()-g.getTime())/1E3,f=Math.abs(d);if(!isNaN(d)&&!(!b.format_future&&d<0||!b.format_past&&d>0)){for(var j in b.units){var e=b.units[j];if(!(e.past_only&&d<0||e.future_only&&
d>0)&&f<e.limit){if(isNaN(e.in_seconds))return c(e.name,NaN,b);f/=e.in_seconds;f=Math.round(f);return(d<0?c("future_format",NaN,b).replace("%s",c("in",NaN,b)):c("past_format",NaN,b).replace("%s",c("ago",NaN,b))).replace("%t",f+" "+c(e.name,f,b))}}return b.uneasy_format(g)}}})(jQuery);
/*
* hogan.js
*/
var HoganTemplate=function(){function n(a){this.text=a}n.prototype={r:function(){return""},v:function(a){a=String(a===null?"":a);return s.test(a)?a.replace(u,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(l,"&#39;").replace(j,"&quot;"):a},render:function(a,c,f){return this.r(a,c,f)},rp:function(a,c,f,e){a=f[a];return!a?"":a.r(c,f,e)},rs:function(a,c,f){var e="",g=a[a.length-1];if(!p(g))return f(a,c);for(var b=0;b<g.length;b++)a.push(g[b]),e+=f(a,c),a.pop();return e},s:function(a,c,f,e,g,b,i){if(p(a)&&
a.length===0)return!1;!e&&typeof a=="function"&&(a=this.ls(a,c,f,g,b,i));f=a===""||!!a;!e&&f&&c&&c.push(typeof a=="object"?a:c[c.length-1]);return f},d:function(a,c,f,e){var g=a.split("."),b=this.f(g[0],c,f,e),i=null;if(a==="."&&p(c[c.length-2]))return c[c.length-1];for(a=1;a<g.length;a++)b&&typeof b=="object"&&g[a]in b?(i=b,b=b[g[a]]):b="";if(e&&!b)return!1;!e&&typeof b=="function"&&(c.push(i),b=this.lv(b,c,f),c.pop());return b},f:function(a,c,f,e){for(var g=!1,b=null,i=!1,m=c.length-1;m>=0;m--)if((b=
c[m])&&typeof b=="object"&&a in b){g=b[a];i=!0;break}if(!i)return e?!1:"";!e&&typeof g=="function"&&(g=this.lv(g,c,f));return g},ho:function(a,c,f,e,g){a=a.call(c,e,function(b){return Hogan.compile(b,{delimiters:g}).render(c,f)});this.b=Hogan.compile(a.toString(),{delimiters:g}).render(c,f);return!1},b:"",ls:function(a,c,f,e,g,b){var c=c[c.length-1],i=a.call(c);return a.length>0?this.ho(a,c,f,this.text.substring(e,g),b):typeof i=="function"?this.ho(i,c,f,this.text.substring(e,g),b):i},lv:function(a,
c,f){c=c[c.length-1];return Hogan.compile(a.call(c).toString()).render(c,f)}};var u=/&/g,v=/</g,w=/>/g,l=/\'/g,j=/\"/g,s=/[&<>\"\']/,p=Array.isArray||function(a){return Object.prototype.toString.call(a)==="[object Array]"};return n}(),Hogan=function(){function n(b,a){function m(){o.length>0&&(k.push(new String(o)),o="")}function c(b,a){m();var d;if(d=b)a:{d=!0;for(var i=n;i<k.length;i++)if(d=k[i].tag&&g[k[i].tag]<g._v||!k[i].tag&&k[i].match(p)===null,!d){d=!1;break a}}if(d){d=n;for(var f;d<k.length;d++)if(!k[d].tag){if((f=
k[d+1])&&f.tag==">")f.indent=k[d].toString();k.splice(d,1)}}else a||k.push({tag:"\n"});j=!1;n=k.length}function d(b,a){var d="="+q,m=b.indexOf(d,a),c=u(b.substring(b.indexOf("=",a)+1,m)).split(" ");r=c[0];q=c[1];return m+d.length-1}var f=b.length,e=0,t=null,l=null,o="",k=[],j=!1,h=0,n=0,r="{{",q="}}";a&&(a=a.split(" "),r=a[0],q=a[1]);for(h=0;h<f;h++)e==0?v(r,b,h)?(--h,m(),e=1):b.charAt(h)=="\n"?c(j):o+=b.charAt(h):e==1?(h+=r.length-1,t=(l=g[b.charAt(h+1)])?b.charAt(h+1):"_v",t=="="?(h=d(b,h),e=0):
(l&&h++,e=2),j=h):v(q,b,h)?(k.push({tag:t,n:u(o),otag:r,ctag:q,i:t=="/"?j-q.length:h+r.length}),o="",h+=q.length-1,e=0,t=="{"&&h++):o+=b.charAt(h);c(j,!0);return k}function u(b){return b.trim?b.trim():b.replace(/^\s*|\s*$/g,"")}function v(b,a,m){if(a.charAt(m)!=b.charAt(0))return!1;for(var c=1,d=b.length;c<d;c++)if(a.charAt(m+c)!=b.charAt(c))return!1;return!0}function w(b,a,c,f){for(var a=[],d=null,e=null;b.length>0;){e=b.shift();if(!(d=e.tag=="#"))if(!(d=e.tag=="^"))a:{for(var d=e,g=f,j=0,l=g.length;j<
l;j++)if(g[j].o==d.n){d.tag="#";d=!0;break a}d=void 0}if(d)c.push(e),e.nodes=w(b,e.tag,c,f),a.push(e);else if(e.tag=="/"){if(c.length===0)throw Error("Closing tag without opener: /"+e.n);d=c.pop();if(b=e.n!=d.n){var o;a:{b=0;for(c=f.length;b<c;b++)if(f[b].c==e.n&&f[b].o==d.n){o=!0;break a}}b=!o}if(b)throw Error("Nesting error: "+d.n+" vs. "+e.n);d.end=e.i;return a}else a.push(e)}if(c.length>0)throw Error("missing closing tag: "+c.pop().n);return a}function l(b){return b.replace(e,"\\\\").replace(a,
'\\"').replace(c,"\\n").replace(f,"\\r")}function j(b){return~b.indexOf(".")?"d":"f"}function s(b){for(var a="",c=0,e=b.length;c<e;c++){var d=b[c].tag;if(d=="#"){var d=b[c].nodes,f=j(b[c].n),g=b[c].i,n=b[c].end,p=b[c].otag+" "+b[c].ctag,d="if(_.s(_."+f+'("'+l(b[c].n)+'",c,p,1),c,p,0,'+g+","+n+', "'+p+'")){b += _.rs(c,p,function(c,p){ var b = "";'+s(d)+'return b;});c.pop();}else{b += _.b; _.b = ""};';a+=d}else d=="^"?(d=b[c].nodes,d="if (!_.s(_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,1),c,p,1,0,0,"")){'+
s(d)+"};",a+=d):d=="<"||d==">"?a+='b += _.rp("'+l(b[c].n)+'",c[c.length - 1],p,"'+(b[c].indent||"")+'");':d=="{"||d=="&"?(d="b += (_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,0));',a+=d):d=="\n"?a+='b += "\\n"'+(b.length-1==c?"":" + i")+";":d=="_v"?(d="b += (_.v(_."+j(b[c].n)+'("'+l(b[c].n)+'",c,p,0)));',a+=d):d===void 0&&(d='"'+l(b[c])+'"',a+="b += "+d+";")}return a}var p=/\S/,a=/\"/g,c=/\n/g,f=/\r/g,e=/\\/g,g={"#":1,"^":2,"/":3,"!":4,">":5,"<":6,"=":7,_v:8,"{":9,"&":10};return{scan:n,parse:function(b,a){a=
a||{};return w(b,"",[],a.sectionTags||[])},cache:{},compile:function(b,a){var a=a||{},c=this.cache[b];if(c)return c;var e=this.parse(n(b,a.delimiters),a),c=a,e='i = i || "";var c = [cx];var b = i + "";var _ = this;'+s(e)+"return b;";c.asString?c="function(cx,p,i){"+e+";}":(c=new HoganTemplate(b),c.r=new Function("cx","p","i",e));return this.cache[b]=c}}}();
if(typeof module!=="undefined"&&module.exports)module.exports=Hogan,module.exports.Template=HoganTemplate;else if(typeof define==="function"&&define.amd)define(function(){return Hogan});else if(typeof exports!=="undefined")exports.Hogan=Hogan,exports.HoganTemplate=HoganTemplate;
/*
* max.templates.js
*/
var max=max||{};
max.templates=function(){return{mainUI:Hogan.compile('<div id="maxui-container">{{#username}} <div id="maxui-mainpanel">   <div id="maxui-search" class="folded">       <a id="maxui-search-toggle" class="maxui-disabled" href="#"><img src="++resource++transparent.gif" alt="obre-tanca" ></a>       <div id="maxui-search-box">          <input id="maxui-search-text" type="search" placeholder="{{literals.search_text}}" class="maxui-empty maxui-text-input" value="{{literals.search_text}}" />          <\!--<input disabled="disabled" id="maxui-search-action" type="button" class="maxui-button maxui-disabled"></input>--\>       </div>       <div id="maxui-search-filters"></div>   </div>   <div id="maxui-timeline">      <div class="wrapper">          <div id="maxui-preload" class="activities" style="height:0px;overflow:hidden">              <div class="wrapper">              </div>          </div>          <div id="maxui-activities" class="activities">          </div>          <div id="maxui-more-activities">              <input type="button" class="maxui-button" value="{{literals.load_more}}">          </div>      </div>   </div>  </div> </div>{{/username}}{{^username}}  No s\'ha definit cap usuari{{/username}}</div>'),postBox:Hogan.compile('   {{#allowPosting}}   <div id="maxui-newactivity">      <a href="#" class="maxui-avatar">          <img src="{{avatar}}">      </a>      <div id="maxui-newactivity-box">           <textarea class="maxui-empty maxui-text-input">{{literals.new_activity_text}}</textarea>           <input disabled="disabled" type="button" class="maxui-button maxui-disabled" value="{{literals.new_activity_post}}">      </div>   </div>   {{/allowPosting}}'),
activity:Hogan.compile('<div class="maxui-activity" id="{{id}}" userid="{{actor.id}}" username="{{actor.username}}">    <div class="maxui-activity-content">        <div class="maxui-publisheddate">{{date}}</div>        <div class="maxui-author">          <a href="#">           \t\t<span class="maxui-avatar"><img src="{{avatarURL}}"></span>\t\t          <span class="maxui-displayname">{{actor.displayName}}</span>          </a>          <span class="maxui-username">{{actor.username}}</span>        </div>        <div>            <p class="maxui-body">{{&text}}</p>        </div>        <div class="maxui-publisheddate"></div>    </div>    <div class="maxui-footer">        <div class="maxui-origin">               {{#publishedIn}}                   {{literals.context_published_in}}                   <a href="{{publishedIn.url}}">{{publishedIn.displayName}}</a>               {{/publishedIn}}               {{#via}}                   {{literals.generator_via}}                   <span class="maxui-via">                   {{via}}                   </span>               {{/via}}        </div>        <div class="maxui-actions">            <a href="" class="maxui-commentaction">                 {{#replies}}<strong>{{replies.totalItems}}</strong>{{/replies}}                 {{^replies}}<strong>0</strong>{{/replies}}                 {{literals.toggle_comments}}            </a>                    </div>    </div>    <div class="maxui-comments" style="display: none">        <div class="maxui-commentsbox">            {{#replies.items}}                {{> comment}}            {{/replies.items}}        </div>        <div class="maxui-newcommentbox">                <textarea class="maxui-empty maxui-text-input" id="maxui-commentBox">{{literals.new_comment_text}}</textarea>                <input disabled="disabled" type="button" class="maxui-button maxui-disabled" value="{{literals.new_comment_post}}"/>        </div>    </div>    <div class="maxui-clear"></div></div>'),
comment:Hogan.compile('<div class="maxui-comment" id="{{id}}" userid="{{author.id}}" displayname="{{author.username}}">    <div class="maxui-activity-content">        <div class="maxui-publisheddate">{{date}}</div>        <div class="maxui-author">\t   <a href="#">\t\t<span class="maxui-avatar"><img src="{{avatarURL}}"></span>\t\t<span class="maxui-displayname">{{author.displayName}}</span></a> \t   <span class="maxui-username">{{author.username}}</span>        </div>        <div>            <p class="maxui-body">{{&text}}</p>        </div>        <div class="maxui-publisheddate"></div>    </div></div>'),
filters:Hogan.compile('{{#filters}}<div class="maxui-filter maxui-{{type}}" type="{{type}}" value="{{value}}"><span>{{prepend}}{{value}}<a class="close" href=""><img src="++resource++x.png" alt="tanca"></a></span></div>{{/filters}}')}};
/*
* max.literals.js
*/
var max=max||{};
max.literals=function(a){return{en:{new_activity_text:"Write something...",new_activity_post:"Post activity",toggle_comments:"Comments",new_comment_text:"Comment something...",new_comment_post:"Post comment",load_more:"Load more",context_published_in:"Published in",generator_via:"via",search_text:"Search..."},es:{new_activity_text:"Escribe algo...",new_activity_post:"Publica",toggle_comments:"Comentarios",new_comment_text:"Comenta algo...",new_comment_post:"Comenta",load_more:"Cargar m\u00e1s",context_published_in:"Publicado en",
generator_via:"via",search_text:"Busca..."},ca:{new_activity_text:"Escriu alguna cosa...",new_activity_post:"Publica",toggle_comments:"Comentaris",new_comment_text:"Comenta alguna cosa...",new_comment_post:"Comenta",load_more:"Carrega'n m\u00e9s",context_published_in:"Publicat a",generator_via:"via",search_text:"Busca..."}}[a]};
/*
* max.utils.js
*/
var max=max||{};
max.utils=function(){return{normalizeWhiteSpace:function(b,g){var b=b.replace(/(^\s*)|(\s*$)/gi,""),b=b.replace(/\n /,"\n"),e=!0;arguments.length>1&&(e=g);e==!0&&(b=b.replace(/[ ]{2,}/gi," "));return b},formatText:function(b){b&&(b=b.replace(/((https?\:\/\/)|(www\.))(\S+)(\w{2,4})(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/gi,function(b){var e=b;e.match("^https?://")||(e="http://"+e);return'<a href="'+e+'">'+b+"</a>"}),b=b.replace(/(\s|^)#{1}(\w+)/gi,function(b,e,a){return'<a class="maxui-hashtag" href="#" value="'+a+
'">#'+a+" </a>"}));return b},isCORSCapable:function(){return(new XMLHttpRequest).withCredentials!=void 0?!0:!1},formatDate:function(b,g){var e=new Date,a=b.match("^([-+]?)(\\d{4,})(?:-?(\\d{2})(?:-?(\\d{2})(?:[Tt ](\\d{2})(?::?(\\d{2})(?::?(\\d{2})(?:\\.(\\d{1,3})(?:\\d+)?)?)?)?(?:[Zz]|(?:([-+])(\\d{2})(?::?(\\d{2}))?)?)?)?)?)?$");if(a){for(var c=[2,3,4,5,6,7,8,10,11],f=c.length-1;f>=0;--f)a[c[f]]=typeof a[c[f]]!="undefined"&&a[c[f]].length>0?parseInt(a[c[f]],10):0;a[1]=="-"&&(a[2]*=-1);c=Date.UTC(a[2],
a[3]-1,a[4],a[5],a[6],a[7],a[8]);typeof a[9]!="undefined"&&a[9].length>0&&(c+=(a[9]=="+"?-1:1)*(a[10]*36E5+a[11]*6E4));a[2]>=0&&a[2]<=99&&(c-=59958144E6);e.setTime(c);return formatted=jQuery.easydate.format_date(e,g)}else return null},utf8_decode:function(b){var g=[],e=0,a=0,c=0,f=0,m=0;for(b+="";e<b.length;)c=b.charCodeAt(e),c<128?(g[a++]=String.fromCharCode(c),e++):c>191&&c<224?(f=b.charCodeAt(e+1),g[a++]=String.fromCharCode((c&31)<<6|f&63),e+=2):(f=b.charCodeAt(e+1),m=b.charCodeAt(e+2),g[a++]=
String.fromCharCode((c&15)<<12|(f&63)<<6|m&63),e+=3);return g.join("")},sha1:function(b){function g(a,b){return a<<b|a>>>32-b}function e(a){var b="",c,d;for(c=7;c>=0;c--)d=a>>>c*4&15,b+=d.toString(16);return b}var a,c,f=Array(80),m=1732584193,n=4023233417,o=2562383102,p=271733878,q=3285377520,d,h,i,j,k,b=function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);d<128?b+=String.fromCharCode(d):(d>127&&d<2048?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>
12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b}(b);d=b.length;var l=[];for(a=0;a<d-3;a+=4)c=b.charCodeAt(a)<<24|b.charCodeAt(a+1)<<16|b.charCodeAt(a+2)<<8|b.charCodeAt(a+3),l.push(c);switch(d%4){case 0:a=2147483648;break;case 1:a=b.charCodeAt(d-1)<<24|8388608;break;case 2:a=b.charCodeAt(d-2)<<24|b.charCodeAt(d-1)<<16|32768;break;case 3:a=b.charCodeAt(d-3)<<24|b.charCodeAt(d-2)<<16|b.charCodeAt(d-1)<<8|128}for(l.push(a);l.length%16!=14;)l.push(0);l.push(d>>>
29);l.push(d<<3&4294967295);for(b=0;b<l.length;b+=16){for(a=0;a<16;a++)f[a]=l[b+a];for(a=16;a<=79;a++)f[a]=g(f[a-3]^f[a-8]^f[a-14]^f[a-16],1);c=m;d=n;h=o;i=p;j=q;for(a=0;a<=19;a++)k=g(c,5)+(d&h|~d&i)+j+f[a]+1518500249&4294967295,j=i,i=h,h=g(d,30),d=c,c=k;for(a=20;a<=39;a++)k=g(c,5)+(d^h^i)+j+f[a]+1859775393&4294967295,j=i,i=h,h=g(d,30),d=c,c=k;for(a=40;a<=59;a++)k=g(c,5)+(d&h|d&i|h&i)+j+f[a]+2400959708&4294967295,j=i,i=h,h=g(d,30),d=c,c=k;for(a=60;a<=79;a++)k=g(c,5)+(d^h^i)+j+f[a]+3395469782&4294967295,
j=i,i=h,h=g(d,30),d=c,c=k;m=m+c&4294967295;n=n+d&4294967295;o=o+h&4294967295;p=p+i&4294967295;q=q+j&4294967295}k=e(m)+e(n)+e(o)+e(p)+e(q);return k.toLowerCase()}}};
/*
* max.client.js
*/
if(!Object.keys)Object.keys=function(a){var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b};String.prototype.format=function(){var a=arguments;return this.replace(/\{\d+\}/g,function(b){return a[b.match(/\d+/)]})};
function MaxClient(){this.ROUTES={users:"/people",user:"/people/{0}",avatar:"/people/{0}/avatar",user_activities:"/people/{0}/activities",timeline:"/people/{0}/timeline",user_comments:"/people/{0}/comments",user_shares:"/people/{0}/shares",user_likes:"/people/{0}/likes",follows:"/people/{0}/follows",follow:"/people/{0}/follows/{1}",subscriptions:"/people/{0}/subscriptions",activities:"/activities",activity:"/activities/{0}",comments:"/activities/{0}/comments",comment:"/activities/{0}/comments/{1}",
likes:"/activities/{0}/likes",like:"/activities/{0}/likes/{1}",shares:"/activities/{0}/shares",share:"/activities/{0}/shares/{1}"}}MaxClient.prototype.configure=function(a){this.url=a.server;this.mode=a.mode;this.token=a.token;this.actor={objectType:"person",username:a.username}};
MaxClient.prototype.POST=function(a,b,c){maxclient=this;resource_uri="{0}{1}".format(this.url,a);this.mode=="jquery"?jQuery.ajax({url:resource_uri,beforeSend:function(a){a.setRequestHeader("X-Oauth-Token",maxclient.token);a.setRequestHeader("X-Oauth-Username",maxclient.actor.username);a.setRequestHeader("X-Oauth-Scope","widgetcli")},type:"POST",data:JSON.stringify(b),async:!0,dataType:"json"}).done(function(a){c.call(a)}).fail(function(a){jQuery(window).trigger("maxclienterror",a)}):(a={},a[gadgets.io.RequestParameters.CONTENT_TYPE]=
gadgets.io.ContentType.JSON,a[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.POST,a[gadgets.io.RequestParameters.REFRESH_INTERVAL]=1,a[gadgets.io.RequestParameters.POST_DATA]=JSON.stringify(b),a[gadgets.io.RequestParameters.HEADERS]={"X-Oauth-Token":maxclient.token,"X-Oauth-Username":maxclient.actor.username,"X-Oauth-Scope":"widgetcli"},gadgets.io.makeRequest(resource_uri,function(a){c.call(a.data)},a));return!0};
MaxClient.prototype.GET=function(a,b,c){maxclient=this;resource_uri="{0}{1}".format(this.url,a);Object.keys(b).length>0&&(resource_uri+="?"+jQuery.param(b,!0));this.mode=="jquery"?jQuery.ajax({url:resource_uri,beforeSend:function(a){a.setRequestHeader("X-Oauth-Token",maxclient.token);a.setRequestHeader("X-Oauth-Username",maxclient.actor.username);a.setRequestHeader("X-Oauth-Scope","widgetcli")},type:"GET",async:!0,dataType:"json"}).done(function(a){c.call(a)}).fail(function(a){jQuery(window).trigger("maxclienterror",
a)}):(a={},a[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON,a[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.GET,a[gadgets.io.RequestParameters.REFRESH_INTERVAL]=1,a[gadgets.io.RequestParameters.HEADERS]={"X-Oauth-Token":maxclient.token,"X-Oauth-Username":maxclient.actor.username,"X-Oauth-Scope":"widgetcli"},gadgets.io.makeRequest(resource_uri,function(a){c.call(a.data)},a));return!0};
MaxClient.prototype.getUserTimeline=function(a,b){this.GET(this.ROUTES.timeline.format(a),arguments.length>2?arguments[2]:{},b)};MaxClient.prototype.getUserData=function(a,b){this.GET(this.ROUTES.user.format(a),{},b)};MaxClient.prototype.getActivities=function(a,b,c){var d=this.ROUTES.activities;query=arguments.length>3?arguments[3]:{};if(b)query.context=b;this.GET(d,query,c)};MaxClient.prototype.getCommentsForActivity=function(a,b){route=this.ROUTES.comments.format(a);this.GET(route,{},b)};
MaxClient.prototype.addComment=function(a,b,c){var d={actor:{},object:{objectType:"comment",content:""}};d.actor=this.actor;d.object.content=a;route=this.ROUTES.comments.format(b);this.POST(route,d,c)};MaxClient.prototype.addActivity=function(a,b,c){query={object:{objectType:"note",content:""}};if(b.length>0)query.contexts=b;query.object.content=a;if(arguments.length>3)query.generator=arguments[3];route=this.ROUTES.user_activities.format(this.actor.username);this.POST(route,query,c)};
MaxClient.prototype.follow=function(a){query={object:{objectType:"person",username:""}};query.object.username=a;route=this.ROUTES.follow.format(this.actor.username,a);resp=this.POST(route,query)};
/*
* max.ui.js
*/
(function(b){b.fn.maxUI=function(e){var a=this;a.templates=max.templates();a.utils=max.utils();a.language=e.language||"en";var c={maxRequestsAPI:"jquery",maxServerURL:"https://max.upc.edu",readContext:"",writeContexts:[],activitySource:"timeline",literals:max.literals(a.language),enableAlerts:!1};a.settings=b.extend(c,e);if(!a.utils.isCORSCapable()&&a.settings.maxServerURLAlias)a.settings.maxServerURL=a.settings.maxServerURLAlias;a.settings.writeContexts.push(a.settings.readContext);a.settings.readContextHash=
a.utils.sha1(a.settings.readContext);a.settings.avatarURLpattern||(a.settings.avatarURLpattern=a.settings.maxServerURL+"/people/{0}/avatar");a.settings.contextAvatarURLpattern||(a.settings.contextAvatarURLpattern=a.settings.maxServerURL+"/contexts/{0}/avatar");a.settings.enableAlerts&&b(window).bind("maxclienterror",function(a,b){var c=JSON.parse(b.responseText);alert('The server responded with a "{0}" error, with the following message: "{1}". \n\nPlease try again later or contact administrator at admin@max.upc.edu.'.format(c.error,
c.error_description))});this.maxClient=new MaxClient;this.maxClient.configure({server:a.settings.maxServerURL,mode:a.settings.maxRequestsAPI,username:a.settings.username,token:a.settings.oAuthToken});this.maxClient.getUserData(a.settings.username,function(){var c={};if(this.subscribedTo&&this.subscribedTo.items&&this.subscribedTo.items.length>0)for(sc=0;sc<this.subscribedTo.items.length;sc++){var e=this.subscribedTo.items[sc];c[e.url]={};c[e.url].permissions={};for(pm=0;pm<e.permissions.length;pm++)c[e.url].permissions[e.permissions[pm]]=
!0}a.settings.subscriptions=c;c=a.templates.mainUI.render({username:a.settings.username,literals:a.settings.literals});a.html(c);a.printActivities({},function(){b("#maxui-more-activities .maxui-button").click(function(c){c.preventDefault();b("#maxui-search").hasClass("folded")?a.loadMoreActivities():(last_result_id=b(".maxui-activity:last").attr("id"),a.reloadFilters(last_result_id))});b("#maxui-search-toggle").click(function(c){c.preventDefault();b(this).hasClass("maxui-disabled")||(b("#maxui-search").toggleClass("folded"),
b("#maxui-search").hasClass("folded")?a.printActivities({}):a.reloadFilters())});b("#maxui-activities").on("click",".maxui-commentaction",function(a){a.preventDefault();window.status="";b(this).closest(".maxui-activity").find(".maxui-comments").toggle(200)});b("#maxui-activities").on("click",".maxui-author",function(c){c.preventDefault();c=b(this).find(".maxui-username").text();a.addFilter({type:"author",value:c});b("#maxui-search").toggleClass("folded",!1)});b("#maxui-activities").on("click",".maxui-hashtag",
function(c){c.preventDefault();a.addFilter({type:"hashtag",value:b(this).attr("value")});b("#maxui-search").toggleClass("folded",!1)});b("#maxui-search-filters").on("click",".close",function(c){c.preventDefault();c=b(this.parentNode.parentNode);a.delFilter({type:c.attr("type"),value:c.attr("value")})});a.bindActionBehaviour("#maxui-newactivity","#maxui-newactivity-box",a.settings.literals.new_activity_text,function(c){a.sendActivity(c);b("#maxui-search").toggleClass("folded",!0)});a.bindActionBehaviour("#maxui-activities",
".maxui-newcommentbox",a.settings.literals.new_comment_text,function(c){var e=b(this).closest(".maxui-activity").attr("id");a.maxClient.addComment(c,e,function(){b("#activityContainer textarea").val("");var c=this.object.inReplyTo[0].id;a.printCommentsForActivity(c);b("#"+c+" .maxui-newcommentbox textarea").val("");b("#"+c+" .maxui-newcommentbox .maxui-button").attr("disabled","disabled")})});a.bindActionBehaviour("#maxui-search","#maxui-search-box",a.settings.literals.search_text,function(c){a.textSearch(c);
b("#maxui-search").toggleClass("folded",!1)});b("#maxui-search .maxui-text-input").keyup(function(c){c.keyCode==13&&(a.textSearch(b(this).attr("value")),b("#maxui-search").toggleClass("folded",!1))})})});return a};b.fn.bindActionBehaviour=function(e,a,c,d){var g=this,h=a+" .maxui-text-input";b(e).on("focusin",h,function(a){a.preventDefault();text=b(this).val();normalized=g.utils.normalizeWhiteSpace(text,!1);normalized==c&&b(this).val("")}).on("keyup",h,function(a){a.preventDefault();text=b(this).val();
button=b(this).parent().find(".maxui-button");normalized=g.utils.normalizeWhiteSpace(text,!1);normalized==""?(b(button).attr("disabled","disabled"),b(button).attr("class","maxui-button maxui-disabled"),b(this).attr("class","maxui-empty maxui-text-input")):(b(button).removeAttr("disabled"),b(button).attr("class","maxui-button"),b(this).attr("class","maxui-text-input"))}).on("focusout",h,function(a){a.preventDefault();text=b(this).val();normalized=g.utils.normalizeWhiteSpace(text,!1);normalized==""&&
b(this).val(c)}).on("click",a+" .maxui-button",function(a){a.preventDefault();var a=b(this).parent().find(".maxui-text-input").val(),e=g.utils.normalizeWhiteSpace(a,!1);e!=c&e!=""&&d.apply(this,[a])})};b.fn.textSearch=function(b){maxui=this;normalized=maxui.utils.normalizeWhiteSpace(b);b=normalized.split(" ");for(kw=0;kw<b.length;kw++){var a="keyword",c=b[kw];switch(c[0]){case "#":a="hashtag";c=c.substr(1);break;case "@":a="author";c=c.substr(1);break;default:a="keyword"}c.length>=3&&this.addFilter({type:a,
value:c},!1)}this.reloadFilters()};b.fn.reloadFilters=function(){var e={filters:this.filters},a=this.templates.filters.render(e);b("#maxui-search-filters").html(a);a={};for(f=0;f<e.filters.length;f++){var c=e.filters[f];a[c.type]||(a[c.type]=[]);a[c.type].push(c.value)}arguments.length>0&&(a.before=arguments[0]);this.printActivities(a);b("#maxui-search-toggle").toggleClass("maxui-disabled",this.filters.length==0);b("#maxui-search").toggleClass("folded",this.filters.length==0)};b.fn.delFilter=function(b){maxui=
this;var a=!1;for(i=0;i<maxui.filters.length;i++)maxui.filters[i].value==b.value&maxui.filters[i].type==b.type&&(a=!0,maxui.filters.splice(i,1));a&&this.reloadFilters()};b.fn.addFilter=function(b){maxui=this;var a=!0;arguments.length>1&&(a=arguments[1]);if(!maxui.filters)maxui.filters=[];switch(b.type){case "hashtag":b.prepend="#";break;case "author":b.prepend="@";break;default:b.prepend=""}var c=!1;for(i=0;i<maxui.filters.length;i++)maxui.filters[i].value==b.value&maxui.filters[i].type==b.type&&
(c=!0);c||(maxui.filters.push(b),a==!0&&this.reloadFilters())};b.fn.Settings=function(){maxui=this;return maxui.settings};b.fn.sendActivity=function(){maxui=this;var e=b("#maxui-newactivity textarea").val(),a=[];a.push(e);a.push(maxui.settings.writeContexts);a.push(function(){b("#maxui-newactivity textarea").val("");b("#maxui-newactivity .maxui-button").attr("disabled","disabled");var a=b(".maxui-activity:first");a.length>0?(filter={after:a.attr("id")},maxui.printActivities(filter)):maxui.printActivities({})});
maxui.settings.generatorName&&a.push(maxui.settings.generatorName);maxui.maxClient.addActivity.apply(maxui.maxClient,a)};b.fn.loadMoreActivities=function(){maxui=this;filter={before:b(".maxui-activity:last").attr("id")};maxui.printActivities(filter)};b.fn.formatActivities=function(e,a){var c="";for(i=0;i<e.length;i++){var d=e[i],g=void 0;d.hasOwnProperty("contexts")&&d.contexts.length>0&&(g=d.contexts[0]);var h=void 0;if(d.hasOwnProperty("generator")&&d.generator!=this.settings.generatorName)h=d.generator;
var k="";d.actor.objectType=="person"?k=this.settings.avatarURLpattern.format(d.actor.username):d.actor.objectType=="context"&&(k=this.settings.contextAvatarURLpattern.format(d.actor.urlHash));var l=void 0;if(d.replies&&(l={totalItems:d.replies.totalItems,items:[]},d.replies.items.length>0))for(r=0;r<d.replies.items.length;r++){var j=d.replies.items[r];reply={id:j.id,author:j.author,date:this.utils.formatDate(j.published,this.language),text:this.utils.formatText(j.content),avatarURL:this.settings.avatarURLpattern.format(j.author.username)};
l.items.push(reply)}d={id:d.id,actor:d.actor,literals:this.settings.literals,date:this.utils.formatDate(d.published,this.language),text:this.utils.formatText(d.object.content),replies:l,avatarURL:k,publishedIn:g,via:h};c+=this.templates.activity.render(d,{comment:this.templates.comment})}if(a=="beggining"){b("#maxui-preload .wrapper").prepend(c);g=b("#maxui-preload .wrapper .maxui-activity");for(i=d=0;i<g.length;i++)d+=b(g[i]).height()+18;g=b("#maxui-preload").height();b("#maxui-preload").height(d-
g);b("#maxui-preload").css({"margin-top":(d-g)*-1});b("#maxui-preload").animate({"margin-top":0},200,function(){b("#maxui-preload .wrapper").html("");b("#maxui-activities").prepend(c);b("#maxui-preload").height(0)})}else a=="end"?b("#maxui-activities").append(c):b("#maxui-activities").html(c);arguments.length>2&&arguments[2].call()};b.fn.formatComment=function(e,a){maxui=this;var c="";for(i=0;i<e.length;i++){var d=e[i],d={literals:maxui.settings.literals,id:d.id,author:d.author,date:maxui.utils.formatDate(d.published,
maxui.language),text:maxui.utils.formatText(d.content),avatarURL:maxui.settings.avatarURLpattern.format(d.author.username)};c+=maxui.templates.comment.render(d)}b(".maxui-activity#"+a+" .maxui-commentsbox").html(c);comment_count=b(".maxui-activity#"+a+" .maxui-commentaction strong");b(comment_count).text(eval(b(comment_count).text())+1)};b.fn.printActivities=function(e){var a=this,c=[],d="replace";e.before&&(d="end");e.after&&(d="beggining");if(a.settings.activitySource=="timeline"){var g=this.maxClient.getUserTimeline;
c.push(a.settings.username)}else if(a.settings.activitySource=="activities")g=this.maxClient.getActivities,c.push(a.settings.username),c.push(a.settings.readContextHash);if(arguments.length>1){var h=arguments[1];c.push(function(){var c=!0,e=a.settings.subscriptions;if(!e[this.context.url])e[this.context.url]={},e[this.context.url].permissions={},e[this.context.url].permissions.read=this.context.permissions.read=="public",e[this.context.url].permissions.write=!1;for(wc=0;wc<a.settings.writeContexts.length;wc++){var g=
a.settings.writeContexts[wc];e[g].permissions?e[g].permissions.write==!1&&(c=!1):c=!1}c&&(c=b.extend(a.settings,{avatar:a.settings.avatarURLpattern.format(a.settings.username),allowPosting:c,literals:a.settings.literals}),c=a.templates.postBox.render(c),jQuery("#maxui-mainpanel").prepend(c));a.formatActivities(this.items,d,h)})}else c.push(function(){a.formatActivities(this.items,d)});c.push(e);g.apply(this.maxClient,c)};b.fn.printCommentsForActivity=function(b){var a=this,c=[];c.push(b);c.push(function(){a.formatComment(this.items,
b)});this.maxClient.getCommentsForActivity.apply(this.maxClient,c)}})(jQuery);
/*
* max.loader.js
*/
window.setTimeout(function () {
    if(window._MAXUI.onReady && !window._MAXUI.hasRun){
        window._MAXUI.hasRun = true;
        _MAXUI.onReady();
    }
  },0)
